package com.ims.IMS.model.Enum;

public enum InsectNumber {
    RICE_LEAF_ROLLER(1, "rice leaf roller"),
    RICE_LEAF_CATERPILLAR(2, "rice leaf caterpillar"),
    PADDY_STEM_MAGGOT(3, "paddy stem maggot"),
    ASIATIC_RICE_BORER(4, "asiatic rice borer"),
    YELLOW_RICE_BORER(5, "yellow rice borer"),
    RICE_GALL_MIDGE(6, "rice gall midge"),
    RICE_STEMFLY(7, "Rice Stemfly"),
    BROWN_PLANT_HOPPER(8, "brown plant hopper"),
    WHITE_BACKED_PLANT_HOPPER(9, "white backed plant hopper"),
    SMALL_BROWN_PLANT_HOPPER(10, "small brown plant hopper"),
    RICE_WATER_WEEVIL(11, "rice water weevil"),
    RICE_LEAFHOPPER(12, "rice leafhopper"),
    GRAIN_SPREADER_THRIPS(13, "grain spreader thrips"),
    RICE_SHELL_PEST(14, "rice shell pest"),
    GRUB(15, "grub"),
    MOLE_CRICKET(16, "mole cricket"),
    WIREWORM(17, "wireworm"),
    WHITE_MARGINED_MOTH(18, "white margined moth"),
    BLACK_CUTWORM(19, "black cutworm"),
    LARGE_CUTWORM(20, "large cutworm"),
    YELLOW_CUTWORM(21, "yellow cutworm"),
    RED_SPIDER(22, "red spider"),
    CORN_BORER(23, "corn borer"),
    ARMY_WORM(24, "army worm"),
    APHIDS(25, "aphids"),
    POTOSIABRE_VITARSIS(26, "Potosiabre vitarsis"),
    PEACH_BORER(27, "peach borer"),
    ENGLISH_GRAIN_APHID(28, "english grain aphid"),
    GREEN_BUG(29, "green bug"),
    BIRD_CHERRY_OATAPHID(30, "bird cherry-oataphid"),
    WHEAT_BLOSSOM_MIDGE(31, "wheat blossom midge"),
    PENTHAELUS_MAJOR(32, "penthaleus major"),
    LONGLEGGED_SPIDER_MITE(33, "longlegged spider mite"),
    WHEAT_PHLOEOTHRIPS(34, "wheat phloeothrips"),
    WHEAT_SAWFLY(35, "wheat sawfly"),
    CERODONTA_DENTICORNIS(36, "cerodonta denticornis"),
    BEET_FLY(37, "beet fly"),
    FLEA_BEETLE(38, "flea beetle"),
    CABBAGE_ARMY_WORM(39, "cabbage army worm"),
    BEET_ARMY_WORM(40, "beet army worm"),
    BEET_SPOT_FLIES(41, "Beet spot flies"),
    MEADOW_MOTH(42, "meadow moth"),
    BEET_WEEVIL(43, "beet weevil"),
    SERICAORIENT_ALISMOTS_CHULSKY(44, "sericaorient alismots chulsky"),
    ALFALFA_WEEVIL(45, "alfalfa weevil"),
    FLAX_BUDWORM(46, "flax budworm"),
    ALFALFA_PLANT_BUG(47, "alfalfa plant bug"),
    TARNISHED_PLANT_BUG(48, "tarnished plant bug"),
    LOCUSTOIDEA(49, "Locustoidea"),
    LYTA_POLITA(50, "lytta polita"),
    LEGUME_BLISTER_BEETLE(51, "legume blister beetle"),
    BLISTER_BEETLE(52, "blister beetle"),
    THERIOAPHIS_MACULATA_BUCKTON(53, "therioaphis maculata Buckton"),
    ODONTOTHRIPS_LOTI(54, "odontothrips loti"),
    THRIPS(55, "Thrips"),
    ALFALFA_SEED_CHALCID(56, "alfalfa seed chalcid"),
    PIERIS_CANIDIA(57, "Pieris canidia"),
    APOLYGUS_LUCORUM(58, "Apolygus lucorum"),
    LIMACODIDAE(59, "Limacodidae"),
    VITEUS_VITIFOLIAE(60, "Viteus vitifoliae"),
    COLMERUS_VITIS(61, "Colomerus vitis"),
    BREVIPOALPUS_LEWISI_MC_GREGOR(62, "Brevipoalpus lewisi McGregor"),
    OIDES_DECEMPNUCTATA(63, "oides decempunctata"),
    POLYPHAGOTARS_ONEMUS_LATUS(64, "Polyphagotars onemus latus"),
    PSEUDOCOCCUS_COMSTOCKI_KUWANA(65, "Pseudococcus comstocki Kuwana"),
    PARATHRENE_REGALIS(66, "parathrene regalis"),
    AMPELOPHAGA(67, "Ampelophaga"),
    LYCORMA_DELICATULA(68, "Lycorma delicatula"),
    XYLOTRECHUS(69, "Xylotrechus"),
    CICADELLA_VIRIDIS(70, "Cicadella viridis"),
    MIRIDAE(71, "Miridae"),
    TRIALEURODES_VAPORARIORUM(72, "Trialeurodes vaporariorum"),
    ERYTHRONEURA_APICALIS(73, "Erythroneura apicalis"),
    PAPILIO_XUTHUS(74, "Papilio xuthus"),
    PANONCHUS_CITRI_MC_GREGOR(75, "Panonchus citri McGregor"),
    PHYLLOCOPTES_OLEIVERUS_ASHMEAD(76, "Phyllocoptes oleiverus ashmead"),
    ICERYA_PURCHASI_MASKELL(77, "Icerya purchasi Maskell"),
    UNASPIS_YANONENSIS(78, "Unaspis yanonensis"),
    CEROPLASTES_RUBENS(79, "Ceroplastes rubens"),
    CHRYSOMPHALUS_AONIDUM(80, "Chrysomphalus aonidum"),
    PARLATORIA_ZIZYPHUS_LUCUS(81, "Parlatoria zizyphus Lucus"),
    NIPAECOCCUS_VASTALOR(82, "Nipaecoccus vastalor"),
    ALEUROCANTHUS_SPINIFERUS(83, "Aleurocanthus spiniferus"),
    TETRADACUS_C_BACTROCERA_MINAX(84, "Tetradacus c Bactrocera minax"),
    DACUS_DORSALIS_HENDEL(85, "Dacus dorsalis(Hendel)"),
    BACTROCERA_TSUNEONIS(86, "Bactrocera tsuneonis"),
    PRODENIA_LITURA(87, "Prodenia litura"),
    ADRISTYRANNUS(88, "Adristyrannus"),
    PHYLLOCNISTIS_CITRELLA_STAINTON(89, "Phyllocnistis citrella Stainton"),
    TOXOPTERA_CITRICIDUS(90, "Toxoptera citricidus"),
    TOXOPTERA_AURANTII(91, "Toxoptera aurantii"),
    APHIS_CITRICOLA_VANDER_GOOT(92, "Aphis citricola Vander Goot"),
    SCIRTOTHRIPS_DORSALIS_HOOD(93, "Scirtothrips dorsalis Hood"),
    DASINEURA_SP(94, "Dasineura sp"),
    LAWANAIMITATA_MELICHAR(95, "Lawana imitata Melichar"),
    SALURNIS_MARGINELLA_GUERR(96, "Salurnis marginella Guerr"),
    DEPOREUS_MARGINATUS_PASCOE(97, "Deporaus marginatus Pascoe"),
    CHLUMETIA_TRANSVERSA(98, "Chlumetia transversa"),
    MANGO_FLAT_BEAK_LEAFHOPPER(99, "Mango flat beak leafhopper"),
    RHYTIDODERA_BOWRINII_WHITE(100, "Rhytidodera bowrinii white"),
    STERNOCHEUTUS_FRIGIDUS(101, "Sternochetus frigidus"),
    CICADELLIDAE(102, "Cicadellidae");

    private final int number;
    private final String description;

    InsectNumber(int number, String description) {
        this.number = number;
        this.description = description;
    }

    public int getNumber() {
        return number;
    }

    public String getDescription() {
        return description;
    }
}
