name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/saty-ai/saty-be:latest --push .
        env:
          MAVEN_OPTS: "-X -e"  # Enable debug and error logging

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          script: |
            cd saty-be
            docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose --profile prod stop app
            docker compose --profile prod rm -f app
            docker compose --profile prod pull app
            docker compose --profile prod up -d app
            # Post deployment cleanup
            docker system prune -f
            docker logout ghcr.io